default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  timeout: 5000

development:
  <<: *default
  database: cervejeira_app

test:
  <<: *default
  database: cervejeira_app_test

production:
  <<: *default
  database: cervejeira_app
